import { writeFileSync } from 'node:fs';
import { generatePuzzles } from './generator/core';
import type { Puzzle } from './types';

const renderTS = (puzzles: Puzzle[]): string => {
  const out: string[] = [];
  out.push(`// Auto-generated by src/puzzles/generate.ts. Do not edit by hand.`);
  out.push(`import type { Puzzle } from '../types';`);
  out.push(``);
  out.push(`export const GENERATED_PUZZLES: Puzzle[] = [`);
  for (const p of puzzles) {
    out.push(`  {`);
    out.push(`    id: ${JSON.stringify(p.id)},`);
    out.push(`    category: ${JSON.stringify(p.category)},`);
    out.push(`    difficulty: ${p.difficulty},`);
    out.push(`    size: ${p.size},`);
    out.push(`    toPlay: ${JSON.stringify(p.toPlay)},`);
    out.push(`    setup: [`);
    for (const row of p.setup.split('\n')) {
      out.push(`      ${JSON.stringify(row)},`);
    }
    out.push(`    ].join('\\n'),`);
    const stepsJson = p.lines[0]!.steps
      .map((s) => {
        const u = `user: { x: ${s.user.x}, y: ${s.user.y} }`;
        const b = s.bot ? `, bot: { x: ${s.bot.x}, y: ${s.bot.y} }` : '';
        return `{ ${u}${b} }`;
      })
      .join(', ');
    out.push(`    lines: [{ steps: [${stepsJson}] }],`);
    if (p.hint) out.push(`    hint: ${JSON.stringify(p.hint)},`);
    if (p.description) out.push(`    description: ${JSON.stringify(p.description)},`);
    out.push(`  },`);
  }
  out.push(`];`);
  return out.join('\n') + '\n';
};

const main = () => {
  const puzzles = generatePuzzles({
    count: 32,
    maxSteps: 4,
    seed: 424242,
    size: 9,
    maxGames: 250,
  });
  const path = 'src/puzzles/data/generated.ts';
  writeFileSync(path, renderTS(puzzles));
  console.log(`Wrote ${puzzles.length} puzzles to ${path}`);
};

main();
